"""add_performance_indexes

Revision ID: 01b2403b451f
Revises: 
Create Date: 2026-04-28 22:05:51.540216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b2403b451f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    def has_index(table_name, index_name):
        indexes = inspector.get_indexes(table_name)
        return any(idx['name'] == index_name for idx in indexes)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        if not has_index('attendance', 'ix_att_student_date'):
            batch_op.create_index('ix_att_student_date', ['student_id', 'date'], unique=False)
        if not has_index('attendance', 'ix_att_subject_date'):
            batch_op.create_index('ix_att_subject_date', ['subject_id', 'date'], unique=False)
        if not has_index('attendance', 'ix_att_subject_status'):
            batch_op.create_index('ix_att_subject_status', ['subject_id', 'status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        if not has_index('notifications', 'ix_notifications_created_at'):
            batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        if not has_index('notifications', 'ix_notifications_is_read'):
            batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        if not has_index('notifications', 'ix_notifications_user_id'):
            batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        if not has_index('students', 'ix_students_approval_status'):
            batch_op.create_index(batch_op.f('ix_students_approval_status'), ['approval_status'], unique=False)
        if not has_index('students', 'ix_students_class_id'):
            batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        if not has_index('students', 'ix_students_prn'):
            batch_op.create_index(batch_op.f('ix_students_prn'), ['prn'], unique=True)
        if not has_index('students', 'ix_students_roll_no'):
            batch_op.create_index(batch_op.f('ix_students_roll_no'), ['roll_no'], unique=False)
        if not has_index('students', 'ix_students_tg_id'):
            batch_op.create_index(batch_op.f('ix_students_tg_id'), ['tg_id'], unique=False)
        if not has_index('students', 'ix_students_user_id'):
            batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        if not has_index('subjects', 'ix_subjects_class_id'):
            batch_op.create_index(batch_op.f('ix_subjects_class_id'), ['class_id'], unique=False)
        if not has_index('subjects', 'ix_subjects_teacher_id'):
            batch_op.create_index(batch_op.f('ix_subjects_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        if not has_index('teachers', 'ix_teachers_department_id'):
            batch_op.create_index(batch_op.f('ix_teachers_department_id'), ['department_id'], unique=False)
        if not has_index('teachers', 'ix_teachers_user_id'):
            batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        if not has_index('users', 'ix_users_email'):
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        if not has_index('users', 'ix_users_role'):
            batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        if not has_index('users', 'ix_users_status'):
            batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_department_id'))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_class_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_tg_id'))
        batch_op.drop_index(batch_op.f('ix_students_roll_no'))
        batch_op.drop_index(batch_op.f('ix_students_prn'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))
        batch_op.drop_index(batch_op.f('ix_students_approval_status'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_att_subject_status')
        batch_op.drop_index('ix_att_subject_date')
        batch_op.drop_index('ix_att_student_date')

    # ### end Alembic commands ###
