"""add practical event sessions and student batch field

Revision ID: 08e592e19ef3
Revises: 01b2403b451f
Create Date: 2026-04-29 20:18:04.124116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e592e19ef3'
down_revision = '01b2403b451f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
