"""add must_change_password to users

Revision ID: 1748ff1e3f6a
Revises: 08e592e19ef3
Create Date: 2026-04-30 01:10:31.139109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1748ff1e3f6a'
down_revision = '08e592e19ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
