"""remove_fee_tables

Revision ID: 3125ee17c929
Revises: ddf66c0d69dd
Create Date: 2026-05-06 17:13:38.474339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3125ee17c929'
down_revision = 'ddf66c0d69dd'
branch_labels = None
depends_on = None


def upgrade():
    # Drop in correct FK dependency order using CASCADE
    op.execute('DROP TABLE IF EXISTS fee_structure_category_rates CASCADE')
    op.execute('DROP TABLE IF EXISTS fee_transactions CASCADE')
    op.execute('DROP TABLE IF EXISTS student_fees CASCADE')
    op.execute('DROP TABLE IF EXISTS dept_fee_summaries CASCADE')
    op.execute('DROP TABLE IF EXISTS fee_structures CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_structure_category_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fee_structure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], name=op.f('fee_structure_category_rates_fee_structure_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_structure_category_rates_pkey')),
    sa.UniqueConstraint('fee_structure_id', 'category', name=op.f('uq_fee_category_rate'))
    )
    with op.batch_alter_table('fee_structure_category_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structure_category_rates_fee_structure_id'), ['fee_structure_id'], unique=False)

    op.create_table('student_fees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_structure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_due', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('scholarship_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('late_fee_added', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], name=op.f('student_fees_fee_structure_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_fees_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_fees_pkey')),
    sa.UniqueConstraint('student_id', 'fee_structure_id', name=op.f('uq_student_fee_structure'))
    )
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_fee_structure'), ['fee_structure_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fee_status'), ['student_id', 'status'], unique=False)

    op.create_table('fee_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('provider_ref_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('student_fee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_instrument', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('phonepe_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('receipt_path', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], name=op.f('fee_transactions_student_fee_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fee_transactions_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_transactions_pkey'))
    )
    with op.batch_alter_table('fee_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_txn_student_status'), ['student_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_txn_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fee_transactions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_transactions_student_fee_id'), ['student_fee_id'], unique=False)

    op.create_table('fee_structures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('late_fee_per_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fee_structures_class_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fee_structures_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fee_structures_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_structures_pkey'))
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_struct_class_sem'), ['class_id', 'semester', 'academic_year'], unique=False)

    op.create_table('dept_fee_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_students', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partial_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unpaid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_collected', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_pending', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('dept_fee_summaries_class_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('dept_fee_summaries_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dept_fee_summaries_pkey')),
    sa.UniqueConstraint('class_id', 'academic_year', 'semester', name=op.f('uq_summary_class_sem_year'))
    )
    with op.batch_alter_table('dept_fee_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dept_fee_summaries_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dept_fee_summaries_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###
