"""add otp_requests table

Revision ID: 932bbe95883f
Revises: 1d0939bd81bd
Create Date: 2026-05-01 21:39:35.879402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932bbe95883f'
down_revision = '1d0939bd81bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=50), nullable=True))

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.create_index('ix_marks_student_subject', ['student_id', 'subject_id'], unique=False)
        batch_op.create_unique_constraint('uq_marks_student_subject_exam', ['student_id', 'subject_id', 'exam_type'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_unread', ['user_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_user_unread')

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_marks_student_subject_exam', type_='unique')
        batch_op.drop_index('ix_marks_student_subject')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('module')

    # ### end Alembic commands ###
