"""add count_in_attendance to subjects

Revision ID: b36e8c4f9f84
Revises: cdfc00de9424
Create Date: 2026-05-05 12:43:14.456158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36e8c4f9f84'
down_revision = 'cdfc00de9424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_in_attendance', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('count_in_attendance')

    # ### end Alembic commands ###
