"""add attachment to notices

Revision ID: cdfc00de9424
Revises: bba8d69cd7a5
Create Date: 2026-05-05 12:12:28.744306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfc00de9424'
down_revision = 'bba8d69cd7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_created_by'))
        batch_op.drop_index(batch_op.f('ix_assignments_deadline'))
        batch_op.drop_index(batch_op.f('ix_assignments_subject_id'))

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_status'))
        batch_op.drop_index(batch_op.f('ix_certificates_student_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_type'))

    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievances_assigned_to'))
        batch_op.drop_index(batch_op.f('ix_grievances_created_at'))
        batch_op.drop_index(batch_op.f('ix_grievances_status'))
        batch_op.drop_index(batch_op.f('ix_grievances_student_id'))

    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaves_created_at'))
        batch_op.drop_index(batch_op.f('ix_leaves_ct_status'))
        batch_op.drop_index(batch_op.f('ix_leaves_start_date'))
        batch_op.drop_index(batch_op.f('ix_leaves_student_id'))
        batch_op.drop_index(batch_op.f('ix_leaves_tg_status'))

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=300), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notices_created_at'))
        batch_op.drop_index(batch_op.f('ix_notices_posted_by'))
        batch_op.drop_index(batch_op.f('ix_notices_status_deleted'))
        batch_op.drop_index(batch_op.f('ix_notices_target_class_id'))
        batch_op.drop_index(batch_op.f('ix_notices_target_role'))

    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetable_class_day'))
        batch_op.drop_index(batch_op.f('ix_timetable_start_time'))
        batch_op.drop_index(batch_op.f('ix_timetable_subject_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetable_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetable_class_day'), ['class_id', 'day'], unique=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_target_role'), ['target_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_target_class_id'), ['target_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_status_deleted'), ['status', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_posted_by'), ['posted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('attachment')

    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaves_tg_status'), ['tg_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaves_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaves_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaves_ct_status'), ['ct_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaves_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievances_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_assigned_to'), ['assigned_to'], unique=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_status'), ['status'], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###
