"""add_fee_category_rates

Revision ID: ddf66c0d69dd
Revises: e6544514d3a5
Create Date: 2026-05-06 16:54:24.849636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf66c0d69dd'
down_revision = 'e6544514d3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_structure_category_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_structure_id', 'category', name='uq_fee_category_rate')
    )
    with op.batch_alter_table('fee_structure_category_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structure_category_rates_fee_structure_id'), ['fee_structure_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structure_category_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structure_category_rates_fee_structure_id'))

    op.drop_table('fee_structure_category_rates')
    # ### end Alembic commands ###
