"""fee_management_system

Revision ID: e6544514d3a5
Revises: b36e8c4f9f84
Create Date: 2026-05-06 16:32:10.508469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6544514d3a5'
down_revision = 'b36e8c4f9f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept_fee_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('paid_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('unpaid_count', sa.Integer(), nullable=True),
    sa.Column('total_collected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_pending', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'academic_year', 'semester', name='uq_summary_class_sem_year')
    )
    with op.batch_alter_table('dept_fee_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dept_fee_summaries_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dept_fee_summaries_department_id'), ['department_id'], unique=False)

    op.create_table('fee_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('late_fee_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index('ix_fee_struct_class_sem', ['class_id', 'semester', 'academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_department_id'), ['department_id'], unique=False)

    op.create_table('student_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scholarship_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee_added', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', name='uq_student_fee_structure')
    )
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.create_index('ix_student_fee_status', ['student_id', 'status'], unique=False)
        batch_op.create_index('ix_student_fee_structure', ['fee_structure_id', 'status'], unique=False)

    op.create_table('fee_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('provider_ref_id', sa.String(length=120), nullable=True),
    sa.Column('student_fee_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_instrument', sa.String(length=30), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('phonepe_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_transactions_student_fee_id'), ['student_fee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_transactions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index('ix_fee_txn_created', ['created_at'], unique=False)
        batch_op.create_index('ix_fee_txn_student_status', ['student_id', 'status'], unique=False)

    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    with op.batch_alter_table('fee_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_txn_student_status')
        batch_op.drop_index('ix_fee_txn_created')
        batch_op.drop_index(batch_op.f('ix_fee_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_fee_transactions_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_transactions_student_fee_id'))

    op.drop_table('fee_transactions')
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.drop_index('ix_student_fee_structure')
        batch_op.drop_index('ix_student_fee_status')

    op.drop_table('student_fees')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structures_department_id'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_class_id'))
        batch_op.drop_index('ix_fee_struct_class_sem')

    op.drop_table('fee_structures')
    with op.batch_alter_table('dept_fee_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dept_fee_summaries_department_id'))
        batch_op.drop_index(batch_op.f('ix_dept_fee_summaries_class_id'))

    op.drop_table('dept_fee_summaries')
    # ### end Alembic commands ###
